kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: restricted-namespace
  name: deployment-manager
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: 
  - deployments
  - replicasets
  - pods
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch

