apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flask
spec:
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: abhaybhargav/vul_flask_redis
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
