apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  #namespace: prod
spec:
  selector:
    matchLabels:
      app: redis
      #tier: backend
      #track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        #tier: backend
        #track: stable
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              name: redis-port
