apiVersion: v1
kind: Pod
metadata:
  name: flask-apparmor
  labels:
    app: flask
  annotations:
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
    container.apparmor.security.beta.kubernetes.io/flask: localhost/k8s-vul-flask-redis-armor
spec:
  containers:
  - name: flask
    image: abhaybhargav/vul_flask:latest
    ports:
      - containerPort: 5050
        #securityContext:
            #runAsUser: 100
            #runAsNonRoot: true
            #allowPrivilegeEscalation: false
