apiVersion: v1
kind: Pod
metadata:
  name: secure-vul-flask
  annotations:
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
    container.apparmor.security.beta.kubernetes.io/secure-vul-flask: 'localhost/k8s-vul-flask-redis-armor'
  labels:
    app: secure-vul-flask
spec:
  containers:
    - name: nginx
      image: nginx:1.11
      ports:
      - containerPort: 80
      volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: config-volume
    - name: redis
      image: redis
      ports:
      - containerPort: 6379
    - name: secure-vul-flask
      image: abhaybhargav/secure_vul_flask
      imagePullPolicy: Always
      securityContext:
        runAsUser: 100
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      env:
        - name: REDIS_HOST
          value: 127.0.0.1
      ports:
      - containerPort: 5000
        name: vulflask-port
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
